# Generated by Django 5.2.6 on 2025-09-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='designation',
            new_name='designacao',
        ),
    ]
