# Generated by Django 5.2.6 on 2025-09-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estudantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estudante_id', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=50)),
                ('Ramo', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudante',
        ),
    ]
