# Generated by Django 5.2.6 on 2025-09-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudantes', '0002_estudantes_delete_estudante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudantes',
            name='Ramo',
            field=models.CharField(max_length=50),
        ),
    ]
